version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: store_db
    ports:
      - "5433:5432"
    volumes:
      - ./store_db:/var/lib/postgresql/data
